#!/usr/bin/env sh
#
# This script edits a GnuPG protected file by removing a potential
# lock, starting vim for editing and finaly locks it again.
#
# Tom Kazimiers <tom@voodoo-arts.net> / 2011 /Beer-ware

EXPECTED_ARGS=1

# Test arguments
if [ $# -ne $EXPECTED_ARGS ]; then
  echo "Usage: `basename $0` {arg}"
  exit 1
fi

# Test if $EDITOR is set
ED="vim"
if [ "$EDITOR" == "" ]; then
	echo "Info: you do not seem to have \$EDITOR set, please do that. Will use vim."
else
	ED="$EDITOR"
fi

FILENAME=$1
TMPDIR=~/.secret
if [ ! -e $TMPDIR ]; then
    mkdir $TMPDIR
elif [ ! -d $TMPDIR ]; then
    echo "$TMPDIR already exists but is not a directory" 1>&2
    exit 1
fi

gpg -o $TMPDIR/.tmp -d $FILENAME
RETVAL=$?
if [ $RETVAL -ne 0 ]; then
	echo "Error: a problem occured with gpg. Exiting."
	exit 1
fi

$ED $TMPDIR/.tmp
gpg -o $FILENAME -e $TMPDIR/.tmp

# Wipe the temporary file
wipe $TMPDIR/.tmp
RETVAL=$?
if [ $RETVAL -ne 0 ]; then
	echo "Error: a problem occured with wiping the temporary file $TMPDIR/.tmp -- please wipe manually."
	exit 1
else
	echo "Wiped all temporary data successfully."
fi

